#!/usr/bin/env python3
"""Verify pre-built JSON indices match the source SQLite DBs.

Randomly samples headwords/terms and compares JSON index results against
direct DB queries. Use this after rebuilding any index or after changing
normalization logic.

Checks:
  1. headwords.json — every entry exists in dict.sqlite (by headword_norm)
  2. bilex_index.json — skt/tib/zh lookups match bilex.sqlite + equiv table
  3. zone_a.json — snippets match dict.sqlite SUBSTR(body_ko|body, 1, 50)

Exit code: 0 if all pass, 1 on any mismatch.

Usage:
    python3 scripts/verify_indices.py           # default 200 samples per check
    python3 scripts/verify_indices.py --n 500   # larger sample
"""
from __future__ import annotations

import argparse
import json
import random
import sqlite3
import sys
import unicodedata
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from transliterate import normalize_headword, hk_to_iast, devanagari_to_iast  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
BUILD = ROOT / "build"
DOCS = ROOT / "docs"

DICT_DB = BUILD / "dict.sqlite"
BILEX_DB = BUILD / "bilex.sqlite"
HEADWORDS_JSON = DOCS / "headwords.json"
BILEX_INDEX_JSON = DOCS / "bilex_index.json"
ZONE_A_JSON = DOCS / "zone_a.json"


def normalize(s: str) -> str:
    """Mirror JS normalize(): NFD + strip combining marks + lowercase + trim.

    This must stay in sync with bilex.js / lookup.js normalize() so that
    keys generated by Python build scripts match what JS computes at query time.
    """
    if not s:
        return ""
    nfd = unicodedata.normalize("NFD", s)
    no_marks = "".join(ch for ch in nfd if not unicodedata.combining(ch))
    return no_marks.lower().strip()


def check_normalize_roundtrip(sample_n: int) -> tuple[int, int]:
    """Verify every key in bilex_index.json is stable under normalize().

    If a key changes when re-normalized, it means build-time normalization
    diverged from JS runtime normalization — queries will silently miss.
    """
    print(f"\n[pre-check] Verifying normalize() stability on bilex keys...")
    with open(BILEX_INDEX_JSON, "r", encoding="utf-8") as f:
        idx = json.load(f)

    drift = []
    total = 0
    for key_type in ("k", "t", "z"):
        keys = list(idx[key_type].keys())
        sample = random.sample(keys, min(sample_n, len(keys)))
        for k in sample:
            total += 1
            if normalize(k) != k:
                drift.append((key_type, k, normalize(k)))

    if drift:
        print(f"  FAIL: {len(drift)}/{total} keys changed after re-normalize")
        for kt, orig, new in drift[:5]:
            print(f"    [{kt}] {orig!r} → {new!r}")
        return (total - len(drift), len(drift))
    print(f"  OK: all {total} keys stable under normalize()")
    return (total, 0)


# ── Check 1: headwords.json ↔ dict.sqlite ─────────────────────────────

def check_headwords(sample_n: int) -> tuple[int, int]:
    """Verify every sampled entry in headwords.json exists in dict.sqlite."""
    print(f"\n[1/3] Verifying headwords.json ({sample_n} samples)...")
    with open(HEADWORDS_JSON, "r", encoding="utf-8") as f:
        hws = json.load(f)

    if not isinstance(hws, list):
        print(f"  FAIL: expected JSON array, got {type(hws).__name__}")
        return (0, 1)

    sample = random.sample(hws, min(sample_n, len(hws)))
    conn = sqlite3.connect(str(DICT_DB))
    missing = []
    for hw in sample:
        row = conn.execute(
            "SELECT 1 FROM entries WHERE headword_norm = ? LIMIT 1", (hw,)
        ).fetchone()
        if not row:
            missing.append(hw)
    conn.close()

    if missing:
        print(f"  FAIL: {len(missing)}/{len(sample)} headwords not in DB")
        for hw in missing[:5]:
            print(f"    missing: {hw!r}")
        return (len(sample) - len(missing), len(missing))
    print(f"  OK: all {len(sample)} sampled headwords found in dict.sqlite")
    return (len(sample), 0)


# ── Check 2: bilex_index.json ↔ bilex.sqlite + equiv ──────────────────

def check_bilex(sample_n: int) -> tuple[int, int]:
    """Verify skt/tib/zh key lookups in bilex_index match DB.

    Since build_bilex_index.py re-normalizes keys via js_normalize(), we must
    apply the same normalization to DB values before comparing counts.
    """
    print(f"\n[2/3] Verifying bilex_index.json ({sample_n} samples)...")
    with open(BILEX_INDEX_JSON, "r", encoding="utf-8") as f:
        idx = json.load(f)

    conn = sqlite3.connect(str(BILEX_DB))

    # Pre-compute normalized DB counts for each field, once.
    def build_norm_counts(sql: str) -> dict[str, int]:
        counts: dict[str, int] = {}
        for (val,) in conn.execute(sql):
            if not val:
                continue
            k = normalize(val)
            counts[k] = counts.get(k, 0) + 1
        return counts

    print("  Loading & normalizing DB values (may take ~30s)...")
    skt_counts = build_norm_counts(
        "SELECT skt_norm FROM equiv UNION ALL SELECT skt_norm FROM bilex"
    )
    tib_counts = build_norm_counts(
        "SELECT tib_norm FROM equiv UNION ALL SELECT tib_norm FROM bilex"
    )
    zh_counts = build_norm_counts(
        "SELECT zh_norm FROM equiv WHERE zh_norm != ''"
    )

    fails = 0
    checks = 0

    for key_type, db_counts in [("k", skt_counts), ("t", tib_counts), ("z", zh_counts)]:
        keys = list(idx[key_type].keys())
        if not keys:
            continue
        sample = random.sample(keys, min(sample_n // 3, len(keys)))
        for key in sample:
            checks += 1
            json_count = len(idx[key_type][key])
            db_count = db_counts.get(key, 0)
            # JSON dedups by (skt|tib|src); DB may have duplicates. So
            # JSON count <= DB count is the expected invariant.
            if json_count > db_count:
                fails += 1
                if fails <= 5:
                    print(f"  FAIL [{key_type}]: {key!r} — JSON has {json_count}, DB (normalized) has {db_count}")

    conn.close()

    if fails:
        print(f"  FAIL: {fails}/{checks} bilex keys have more entries in JSON than DB")
        return (checks - fails, fails)
    print(f"  OK: all {checks} bilex lookups consistent with normalized DB")
    return (checks, 0)


# ── Check 3: zone_a.json ↔ dict.sqlite SUBSTR ─────────────────────────

def check_zone_a(sample_n: int) -> tuple[int, int]:
    """Verify Zone A snippets match dict.sqlite SUBSTR output."""
    print(f"\n[3/3] Verifying zone_a.json ({sample_n} samples)...")
    with open(ZONE_A_JSON, "r", encoding="utf-8") as f:
        za = json.load(f)

    dnames = za["d"]
    idx = za["i"]
    keys = list(idx.keys())
    sample = random.sample(keys, min(sample_n, len(keys)))

    conn = sqlite3.connect(str(DICT_DB))
    # Get dict ID for each name
    dict_name_to_id = {}
    for r in conn.execute("SELECT id, name FROM dictionaries"):
        if r[1] in dnames:
            dict_name_to_id[r[1]] = r[0]

    fails = 0
    checks = 0
    for hw in sample:
        entries = idx[hw]
        for di, snippet in entries:
            checks += 1
            dict_name = dnames[di]
            dict_id = dict_name_to_id.get(dict_name)
            if dict_id is None:
                continue
            # Query DB for matching entry
            row = conn.execute(
                "SELECT SUBSTR(COALESCE(body_ko, body, ''), 1, 50) "
                "FROM entries WHERE dict_id = ? AND headword_norm = ? LIMIT 1",
                (dict_id, hw),
            ).fetchone()
            if not row:
                fails += 1
                if fails <= 5:
                    print(f"  FAIL: {hw!r} in {dict_name} — not found in DB")
                continue
            db_snippet = (row[0] or "").replace("\n", " ").strip()
            if db_snippet != snippet:
                fails += 1
                if fails <= 5:
                    print(f"  FAIL: {hw!r} in {dict_name}")
                    print(f"    JSON: {snippet!r}")
                    print(f"    DB:   {db_snippet!r}")
    conn.close()

    if fails:
        print(f"  FAIL: {fails}/{checks} zone_a snippets do not match DB")
        return (checks - fails, fails)
    print(f"  OK: all {checks} zone_a snippets match DB")
    return (checks, 0)


# ── Check 4: cross-script normalization parity ────────────────────────

def _iast_to_hk(s: str) -> str:
    """Reverse-map IAST → HK for testing. Only covers diacritics we use."""
    m = {
        "\u0101": "A", "\u012B": "I", "\u016B": "U",
        "\u1E5B": "R", "\u1E5D": "RR", "\u1E37": "lR", "\u1E39": "lRR",
        "\u1E43": "M", "\u1E25": "H",
        "\u1E45": "G", "\u00F1": "J", "\u1E6D": "T", "\u1E0D": "D", "\u1E47": "N",
        "\u015B": "z", "\u1E63": "S",
    }
    out = []
    for ch in s:
        out.append(m.get(ch, ch))
    return "".join(out)


def check_cross_script(sample_n: int) -> tuple[int, int]:
    """For random IAST headwords, verify HK/Devanagari equivalents normalize
    to the exact same key. This catches any Python↔JS normalization drift."""
    print(f"\n[4/4] Cross-script parity ({sample_n} IAST samples → HK equivalents)...")

    with open(HEADWORDS_JSON, "r", encoding="utf-8") as f:
        hws = json.load(f)

    # Pick IAST-like samples (ASCII letters, likely Sanskrit lowercase + IAST diacritics)
    # Many headwords in the index are already normalized (no diacritics), but
    # the DB contains original forms. Pull a few real originals with diacritics.
    conn = sqlite3.connect(str(DICT_DB))
    rows = conn.execute(
        "SELECT DISTINCT headword FROM entries "
        "WHERE headword GLOB '*[ā-ž]*' AND length(headword) BETWEEN 3 AND 20 "
        "LIMIT 10000"
    ).fetchall()
    conn.close()

    iast_samples = [r[0] for r in rows]
    if not iast_samples:
        print("  SKIP: no IAST headwords with diacritics found")
        return (0, 0)

    sample = random.sample(iast_samples, min(sample_n, len(iast_samples)))
    HK_UPPER = set("AIUTDNSGJRMH")
    fails = 0
    skipped = 0
    for iast in sample:
        norm_iast = normalize_headword(iast)
        hk = _iast_to_hk(iast)
        # Skip cases where reverse-mapped HK lacks any uppercase HK signature.
        # By design, pure-lowercase HK-like strings (e.g. 'vizuddhi' from 'viśuddhi')
        # are NOT auto-converted to avoid mangling English entries containing 'z'.
        # Users needing such cases should type IAST instead.
        if not any(c in HK_UPPER for c in hk):
            skipped += 1
            continue
        norm_hk = normalize_headword(hk)
        if norm_iast != norm_hk:
            fails += 1
            if fails <= 5:
                print(f"  FAIL: {iast!r} → IAST-norm={norm_iast!r}  HK={hk!r} → HK-norm={norm_hk!r}")

    tested = len(sample) - skipped
    if fails:
        print(f"  FAIL: {fails}/{tested} cross-script mismatches (skipped {skipped} pure-z cases)")
        return (tested - fails, fails)
    print(f"  OK: all {tested} IAST↔HK pairs produce identical keys (skipped {skipped} pure-z cases)")
    return (tested, 0)


# ── Main ──────────────────────────────────────────────────────────────

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=200, help="samples per check")
    ap.add_argument("--seed", type=int, default=42, help="random seed")
    args = ap.parse_args()

    random.seed(args.seed)

    for p in [DICT_DB, BILEX_DB, HEADWORDS_JSON, BILEX_INDEX_JSON, ZONE_A_JSON]:
        if not p.exists():
            print(f"ERROR: missing {p}")
            return 1

    total_pass = 0
    total_fail = 0

    for fn in [check_normalize_roundtrip, check_headwords, check_bilex, check_zone_a, check_cross_script]:
        p, f = fn(args.n)
        total_pass += p
        total_fail += f

    print(f"\n{'=' * 60}")
    if total_fail:
        print(f"FAIL: {total_fail} mismatches across {total_pass + total_fail} checks")
        return 1
    print(f"PASS: all {total_pass} checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
